# encoding: UTF-8

table_sqlcreate = {
    "ctp_log": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
               "`content` TEXT NULL,"
               "`gateway` TEXT NULL,"
               "`time` TEXT NULL"
               ")"
               "ENGINE=InnoDB",
    "ctp_tick": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
                "`vtSymbol` TEXT NULL,"
                "`symbol` TEXT NULL,"
                "`exchange` TEXT NULL,"
                "`lastPrice` FLOAT NULL,"
                "`volume` INT NULL,"
                "`openInterest` INT NULL,"
                "`upperLimit` FLOAT NULL,"
                "`lowerLimit` FLOAT NULL,"
                "`date` TEXT NULL,"
                "`time` TEXT NULL,"
                "`datetime` DATETIME(6) NULL,"
                "`bidPrice1` FLOAT NULL,"
                "`bidPrice2` FLOAT NULL,"
                "`bidPrice3` FLOAT NULL,"
                "`bidPrice4` FLOAT NULL,"
                "`bidPrice5` FLOAT NULL,"
                "`askPrice1` FLOAT NULL,"
                "`askPrice2` FLOAT NULL,"
                "`askPrice3` FLOAT NULL,"
                "`askPrice4` FLOAT NULL,"
                "`askPrice5` FLOAT NULL,"
                "`bidVolume1` INT NULL,"
                "`bidVolume2` INT NULL,"
                "`bidVolume3` INT NULL,"
                "`bidVolume4` INT NULL,"
                "`bidVolume5` INT NULL,"
                "`askVolume1` INT NULL,"
                "`askVolume2` INT NULL,"
                "`askVolume3` INT NULL,"
                "`askVolume4` INT NULL,"
                "`askVolume5` INT NULL"
                ")"
                "ENGINE=InnoDB",
    "ctp_1min": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
                "`vtSymbol` TEXT NULL,"
                "`symbol` TEXT NULL,"
                "`exchange` TEXT NULL,"
                "`open` FLOAT NULL,"
                "`high` FLOAT NULL,"
                "`low` FLOAT NULL,"
                "`close` FLOAT NULL,"
                "`date` TEXT NULL,"
                "`time` TEXT NULL,"
                "`datetime` DATETIME(6) NULL,"
                "`volume` INT NULL,"
                "`openInterest` INT NULL"
                ")"
                "ENGINE=InnoDB",
    "ctp_long_position": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
                         "`name` TEXT NULL,"
                         "`vtSymbol` TEXT NULL,"
                         "`long_pos` INT NULL,"
                         "`long_datetime` DATETIME NULL"
                         ")"
                         "ENGINE=InnoDB",
    "ctp_short_position": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
                          "`name` TEXT NULL,"
                          "`vtSymbol` TEXT NULL,"
                          "`short_pos` INT NULL,"
                          "`short_datetime` DATETIME NULL"
                          ")"
                          "ENGINE=InnoDB",
    "ctp_trades": "CREATE TABLE if not exists %(db)s.`%(table)s` ("
                  "`name` TEXT NULL,"
                  "`exchange` TEXT NULL,"
                  "`symbol` TEXT NULL,"
                  "`direction` TEXT NULL,"
                  "`offset` TEXT NULL,"
                  "`price` FLOAT NULL,"
                  "`volume` INT NULL,"
                  "`tradeTime` TEXT NULL,"
                  "`record_datetime` DATETIME(6) NULL"
                  ")"
                  "ENGINE=InnoDB"
}

sql_insert = {
    "ctp_log": "insert into %(db)s.`%(table)s` "
               "(content, time, gateway) "
               "values "
               "('%(content)s', '%(time)s', '%(gateway)s')",
    "ctp_tick": "insert into %(db)s.`%(table)s` "
                "(vtSymbol, symbol, exchange,"
                "lastPrice, volume, openInterest,"
                "upperLimit, lowerLimit, date, time, datetime,"
                "bidPrice1, bidPrice2, bidPrice3, bidPrice4, bidPrice5,"
                "askPrice1, askPrice2, askPrice3, askPrice4, askPrice5,"
                "bidVolume1, bidVolume2, bidVolume3, bidVolume4, bidVolume5,"
                "askVolume1, askVolume2, askVolume3, askVolume4, askVolume5) "
                "values "
                "('%(vtSymbol)s', '%(symbol)s', '%(exchange)s',"
                "%(lastPrice)s, %(volume)s, %(openInterest)s,"
                "%(upperLimit)s, %(lowerLimit)s, '%(date)s', '%(time)s', '%(datetime)s',"
                "%(bidPrice1)s, %(bidPrice2)s, %(bidPrice3)s, %(bidPrice4)s, %(bidPrice5)s,"
                "%(askPrice1)s, %(askPrice2)s, %(askPrice3)s, %(askPrice4)s, %(askPrice5)s,"
                "%(bidVolume1)s, %(bidVolume2)s, %(bidVolume3)s, %(bidVolume4)s, %(bidVolume5)s,"
                "%(askVolume1)s, %(askVolume2)s, %(askVolume3)s, %(askVolume4)s, %(askVolume5)s)",
    "ctp_1min": "insert into %(db)s.`%(table)s` "
                "(vtSymbol, symbol, exchange,"
                "open, high, low, close,"
                "date, time, datetime, volume, openInterest) "
                "values "
                "('%(vtSymbol)s', '%(symbol)s', '%(exchange)s',"
                "%(open)s, %(high)s, %(low)s, %(close)s,"
                "'%(date)s', '%(time)s', '%(datetime)s', %(volume)s, %(openInterest)s)",
    "ctp_long_position": "insert into %(db)s.`%(table)s` "
                         "(name, vtSymbol, long_pos, long_datetime) "
                         "values "
                         "('%(name)s', '%(vtSymbol)s', '%(long_pos)s', '%(tradeTime)s')",
    "ctp_short_position": "insert into %(db)s.`%(table)s` "
                          "(name, vtSymbol, short_pos, short_datetime) "
                          "values "
                          "('%(name)s', '%(vtSymbol)s', '%(short_pos)s', '%(tradeTime)s')",
    "ctp_trades": "insert into %(db)s.`%(table)s` "
                  "(name, exchange, symbol, direction, offset,"
                  "price, volume, tradeTime, record_datetime) "
                  "values "
                  "('%(name)s', '%(exchange)s', '%(symbol)s', '%(direction)s', '%(offset)s',"
                  "'%(price)s', '%(volume)s', '%(tradeTime)s', '%(record_datetime)s')"
}

sql_select = {
    "ctp_log": "select * from %(db)s.`%(table)s`",
    "ctp_tick": "select * from %(db)s.`%(table)s`",
    "ctp_1min": "select * from %(db)s.`%(table)s`",
    "ctp_long_position": "select * from %(db)s.`%(table)s` "
                         "where "
                         "name = '%(name)s' "
                         "and "
                         "vtSymbol = '%(vtSymbol)s'",
    "ctp_short_position": "select * from %(db)s.`%(table)s` "
                          "where "
                          "name = '%(name)s' "
                          "and "
                          "vtSymbol = '%(vtSymbol)s'"
}

sql_update = {
    "ctp_long_position": "update %(db)s.`%(table)s` "
                         "set "
                         "long_pos = %(long_pos)s, "
                         "long_datetime = '%(tradeTime)s'"
                         "where "
                         "name = '%(name)s' "
                         "and "
                         "vtSymbol = '%(vtSymbol)s'",
    "ctp_short_position": "update %(db)s.`%(table)s` "
                          "set "
                          "short_pos = %(short_pos)s, "
                          "short_datetime = '%(tradeTime)s'"
                          "where "
                          "name = '%(name)s' "
                          "and "
                          "vtSymbol = '%(vtSymbol)s'"
}
